name: ASDF Install
author: Dan Drew
description: Install ADSF tools

inputs:
  version:
    default: '0.14.0'
    description: asdf version to install

runs:
  using: composite

  steps:
    - 
      if: ${{ env.ASDF_PLUGINS == '' }}
      shell: bash
      run: |
        echo '::error::No plugin list found. Run tool-versions action first.'
        exit 1

    -
      name: Install asdf
      shell: bash
      run: |
        if asdf --version; then exit 0; fi
        readonly asdf_dir="$HOME/.asdf"

        echo '::group::Installing'
        git clone https://github.com/asdf-vm/asdf.git ${asdf_dir} --branch v${{ inputs.version }}
        echo "${asdf_dir}/bin" >> $GITHUB_PATH
        echo "${asdf_dir}/shims" >> $GITHUB_PATH
        echo '::endgroup::'

    - 
      name: Install asdf plugins
      shell: bash
      run: |
        for plugin in $ASDF_PLUGINS; do
          echo "::group::Installing ${plugin} plugin"
          asdf plugin add ${plugin}
          echo '::endgroup::'
        done

    - 
      name: Install asdf tools
      shell: bash
      run: |
        declare tool_var
        declare tool_version

        for plugin in $ASDF_PLUGINS; do
          tool_var="${plugin^^}_VERSION"
          tool_version=${!tool_var}
          echo "::group::Installing ${plugin} ${tool_version}"
          asdf install ${plugin} ${tool_version}
          echo '::endgroup::'
        done
